v3: Rework the shard manager
diamondburned/arikawa pull request #226
Opened 2021-06-10 23:57 UTC by diamondburned

This pull request reworks the shard manager to be much less intrusive on other packages. Instead of forcing all components to store the shard manager, it now acts as some sort of wrapper over components and manage them directly. The caller no longer needs to do `t.ShardManager.M()` to access the gateway.

A side effect of this pull request is that the `Gateway` type is now embedded into all components. This may make code slightly more confusing, but it shouldn't be too bad.

**Note:** This pull request can NOT be merged from GitHub. It has to be done from the CLI. Reviewers may approve of the pull request still, however. The actual relevant changes are listed at https://github.com/diamondburned/arikawa/commit/66a07389f45cf4908c0b6a08c2342ef32e236ed7.

2021-06-12 20:09 UTC, mavolin requested changes

2021-06-12 20:09 UTC, mavolin commented on _example/sharded/main.go
> +
Remove this blank line.
```suggestion
```

2021-06-12 20:09 UTC, mavolin commented on api/bot.go
> +	return g.URL, nil
This can be simplified to:

```suggestion
	var g BotData
	return g.URL, httputil.NewClient().RequestJSON(&g, "GET", EndpointGateway)
```

2021-06-12 20:09 UTC, mavolin commented on gateway/gateway.go
> +	onScalingRequired func()
There is no `Scaling Required` error code. It's actually `Sharding Required` and I mistyped it. The original shard manager PR fixes this, and so should this.
```suggestion
	onShardingRequired func()
```

2021-06-12 20:09 UTC, mavolin commented on gateway/gateway.go
> +// callback is called.
```suggestion
// OnScalingRequired sets the function to be called if Discord closes with error
// code 4011 aka Sharding Required. When called, the Gateway will already be
// closed, and can (after increasing the number of shards) be reopened using
// Open. Reconnect or ReconnectCtx, however, will not be available as the
// session is invalidated.
//
// The gateway will completely halt what it's doing in the background when this
// callback is called.
```

2021-06-12 20:09 UTC, mavolin commented on gateway/gateway.go
> +	g.onScalingRequired = fn
```suggestion
func (g *Gateway) OnScalingRequired(fn func()) {
	g.onScalingRequired = fn
```
```suggestion
func (g *Gateway) OnShardingRequired(fn func()) {
	g.onShardingRequired = fn
```

2021-06-12 20:09 UTC, mavolin commented on gateway/gateway.go
> +			g.onScalingRequired()
```suggestion
			g.onShardingRequired()
```

2021-06-12 20:09 UTC, mavolin commented on gateway/shard/manager.go
> +	return NewIdentifiedManagerWithURL(url, id, new)
`new` is a built-in function so, even though it's not used in the function, we should opt for another name.
```suggestion
func NewManager(token string, fn NewShardFunc) (*Manager, error) {
	id := gateway.DefaultIdentifier(token)

	url, err := updateIdentifier(context.Background(), id)
	if err != nil {
		return nil, errors.Wrap(err, "failed to get gateway info")
	}

	return NewIdentifiedManagerWithURL(url, id, fn)
```

2021-06-12 20:19 UTC, mavolin commented on gateway/shard/manager.go
> +}
`new` should be replaced here as well.
```suggestion
func NewIdentifiedManagerWithURL(
	url string, id *gateway.Identifier, fn NewShardFunc) (*Manager, error) {

	m := Manager{
		gatewayURL: gateway.AddGatewayParams(url),
		shards:     make([]shard, id.Shard.NumShards()),
		new:        fn,
	}

	var err error

	for i := range m.shards {
		data := id.IdentifyData
		data.Shard = &gateway.Shard{i, len(m.shards)}

		m.shards[i] = shard{
			id: gateway.Identifier{
				IdentifyData:        data,
				IdentifyShortLimit:  id.IdentifyShortLimit,
				IdentifyGlobalLimit: id.IdentifyGlobalLimit,
			},
		}

		m.shards[i].Shard, err = fn(&m, &m.shards[i].id)
		if err != nil {
			return nil, errors.Wrapf(err, "failed to create shard %d/%d", i, len(m.shards)-1)
		}
	}

	return &m, nil
}
```

2021-06-12 20:23 UTC, mavolin commented on gateway/shard/manager.go
> +	}
The mutex won't be unlocked, when returning in L224
```suggestion
	m.mutex.Lock()

	// Exit if we're already rescaling.
	if m.rescaling != nil {
		m.mutex.Unlock()
		return
	}
```

2021-06-14 22:23 UTC, diamondburned commented
Merged into v3 branch manually.

2021-06-14 22:23 UTC, closed without merging