v3: Update more endpoints to Discord API v9
diamondburned/arikawa pull request #230
Opened 2021-06-17 03:48 UTC by samhza

Update message editing/sending for both API and webhooks.

2021-06-17 03:52 UTC, samhza commented
The `embed` field for editing/sending messages has been deprecated in favor of an `embeds` field, allowing for sending/editing multiple embeds in one message. Should EditMessage/EditEmbed's API be kept the same but internally using `Embeds: &[]discord.Embed{embed}` instead of `Embed: embed`? Either way, I think we should remove the `Embed` field from {Send,Edit}MessageData.

https://discord.com/developers/docs/resources/channel#create-message

2021-06-17 20:45 UTC, diamondburned commented
@samhza 

I agree that we should remove the singular Embed field and use the multiple one instead.

2021-06-18 04:22 UTC, diamondburned commented on api/message.go
>  	channelID discord.ChannelID, e discord.Embed) (*discord.Message, error) {
Would `SendEmbed(discord.ChannelID, ...discord.Embed)` be a better API for this?

2021-06-18 04:23 UTC, diamondburned commented on api/message.go
>  	channelID discord.ChannelID, content string, embed *discord.Embed) (*discord.Message, error) {
I think this can also do `SendMessage(discord.ChannelID, string, ...discord.Embed)`.

2021-06-18 04:24 UTC, diamondburned commented on api/message.go
>  	channelID discord.ChannelID, messageID discord.MessageID, embed discord.Embed) (*discord.Message, error) {
(above 2 comments)

2021-06-18 04:27 UTC, diamondburned requested changes

2021-06-18 04:27 UTC, diamondburned commented on utils/sendpart/sendpart.go
> +func Do(method string, c *httputil.Client, data DataMultipartWriter, v interface{}, url string) error {
The order of these arguments should be `Do(c *httputil.Client, method string, data DataMultipartWriter, v interface{}, url string) error`.

2021-06-18 04:27 UTC, diamondburned commented on utils/sendpart/sendpart.go
> +	return Do(http.MethodPost, c, data, v, url)
The `http.Method*` constants probably shouldn't be used here to avoid importing `net/http` just for those constants.

2021-06-18 06:31 UTC, diamondburned approved these changes

2021-06-18 06:32 UTC, merged