feat: add support for disabling signature verification
diamondburned/arikawa pull request #350
Opened 2022-10-11 04:38 UTC by zBNF

During local development it doesn't make a lot of sense to verify signatures IMO.

Here's a proposed change that allows library users to disable verification. I'm open to alternative approaches in order to avoid introducing any breaking changes if there are concerns around that.

2022-10-11 06:50 UTC, diamondburned commented
Discord won't allow using a new endpoint without having the valid signature in the first place.

I'm not sure what you're actually trying to accomplish by having this PR. I personally develop my bot just fine with this. Are you trying to mock test the bot? Why not just call the handler function directly?

2022-10-11 06:50 UTC, diamondburned commented
A non-breaking way to introduce this would be to not do verification if `pubkey == ""`. This way, you can empty out the environment variable for the pubkey within development.

2022-10-11 21:34 UTC, zBNF commented
I think this works.

> Are you trying to mock test the bot?
Basically, I'm looking to run black box tests using mocks on my binary.

2022-10-11 22:49 UTC, diamondburned requested changes

2022-10-11 22:49 UTC, diamondburned commented on api/webhook/interactionserver.go
> -	s.withVerification(http.HandlerFunc(s.handle)).ServeHTTP(w, r)
I think `ServeHTTP` should just be calling `s.httpHandler(w, r)`. I must've introduced the variable but forgot to use it.

2022-10-11 22:49 UTC, diamondburned commented on api/webhook/interactionserver.go
> +	if len(s.pubkey) != 0 {
Change to `s.pubkey != ""`.

2022-10-12 00:17 UTC, zBNF commented on api/webhook/interactionserver.go
> +	if len(s.pubkey) != 0 {
That's invalid.
```invalid operation: cannot compare s.pubkey != "" (mismatched types ed25519.PublicKey and untyped string)```

2022-10-12 01:00 UTC, diamondburned approved these changes

2022-10-12 01:01 UTC, merged