Add support for the new username system
diamondburned/arikawa pull request #393
Opened 2023-06-06 12:33 UTC by starshine-sys

Adds what is currently documented in https://github.com/discord/discord-api-docs/pull/6130. The documentation isn't merged yet, but this has already started rolling out to normal users.

2023-06-07 00:06 UTC, diamondburned commented
Is the `GlobalName` here the display name? AFAIK the new global username is kept the same in the `Username` field?

2023-06-07 00:38 UTC, starshine-sys commented
Yeah, `GlobalName` is the display name--I'm pretty sure the field was originally called `display_name` but it got changed before the rollout.

2023-06-07 02:41 UTC, diamondburned commented
> I'm pretty sure the field was originally called `display_name` but it got changed before the rollout.

Is there a good reason for this? Should we call it `DisplayName` on our end (to match the client) or keep? Does Discord intend to eventually remove display names?

2023-06-07 18:36 UTC, starshine-sys commented
I can't think of any good reason for it being changed other than maybe reducing confusion with server nicknames, so `DisplayName` is probably a better name for it, yeah. I doubt Discord will remove display names because it's prominently shown in the UI and mentioned in all their support articles.

2023-06-07 21:05 UTC, diamondburned commented
Can you make the change? I'll approve the PR afterwards.

2023-06-07 21:06 UTC, diamondburned requested changes

2023-06-07 21:06 UTC, diamondburned commented on discord/user.go
> +	GlobalName    string `json:"global_name"`
`s/GlobalName/DisplayName/`

2023-06-08 00:55 UTC, diamondburned approved these changes

2023-06-08 00:56 UTC, merged

2023-06-09 05:42 UTC, diamondburned commented
In hindsight, `GlobalName` would've been better, since that would allow a `DisplayName() string` method. I will add a `DisplayOrUsername() string` though.